// Applies every migration to an in-memory Postgres (PGlite) and checks the rules the schema promises. No server needed.
import { PGlite } from "@electric-sql/pglite"; import fs from "node:fs"; import assert from "node:assert/strict";
const db = new PGlite(); const dir = new URL("../migrations/", import.meta.url);
for (const f of fs.readdirSync(dir).filter((x) => x.endsWith(".sql")).sort()) for (const s of fs.readFileSync(new URL(f, dir), "utf8").split("--> statement-breakpoint")) await db.exec(s);
const one = async (q, p = []) => (await db.query(q, p)).rows[0]; const rejects = async (q, p = []) => { try { await db.query(q, p); return false; } catch { return true; } };
const tables = (await db.query("select table_name from information_schema.tables where table_schema='public'")).rows.map((r) => r.table_name).sort();
assert.deepEqual(tables, ["applications", "ats_analyses", "coach_conversations", "interview_sessions", "job_skills", "jobs", "refresh_tokens", "resumes", "skills", "users"], "expected tables");
const u = (await one("insert into users(name,email,password_hash) values('A','a@b.c','x') returning id")).id;
const r = (await one("insert into resumes(user_id,title,content) values($1,'R','{}') returning id", [u])).id;
const ats = (s) => rejects("insert into ats_analyses(resume_id,job_description,score,breakdown,matched,missing_evidence,skill_gaps,suggestions,model_version) values($1,'jd',$2,'{}','[]','[]','[]','[]','v')", [r, s]);
assert.equal(await ats(80), false, "valid score accepted"); assert.equal(await ats(150), true, "score above 100 rejected");
assert.equal(await rejects("insert into resumes(user_id,title,content,ats_score) values($1,'R','{}',101)", [u]), true, "resume score above 100 rejected");
assert.equal(await rejects("insert into users(name,email,password_hash) values('B','a@b.c','x')"), true, "duplicate email rejected");
assert.equal(await rejects("insert into applications(user_id,company,title,stage) values($1,'c','t','maybe')", [u]), true, "invalid stage rejected");
const j = (await one("insert into jobs(title,company,source,external_id) values('J','C','seed','s1') returning id")).id;
const s1 = (await one("insert into skills(name) values('React') returning id")).id;
assert.equal(await rejects("insert into skills(name) values('react')"), true, "case-variant duplicate skill rejected");
await db.query("insert into job_skills(job_id,skill_id) values($1,$2)", [j, s1]);
assert.equal(await rejects("insert into job_skills(job_id,skill_id) values($1,$2)", [j, s1]), true, "duplicate job-skill link rejected");
assert.equal((await one("select count(*)::int c from job_skills js join skills s on s.id=js.skill_id where lower(s.name)='react'")).c, 1, "jobs-by-skill query works");
await db.query("insert into interview_sessions(user_id,config,questions) values($1,'{}','[]')", [u]);
assert.equal(await rejects("insert into interview_sessions(user_id,config,questions,status) values($1,'{}','[]','draft')", [u]), true, "invalid session status rejected");
await db.query("insert into coach_conversations(user_id) values($1)", [u]);
assert.equal(await rejects("insert into coach_conversations(user_id) values($1)", [u]), true, "one conversation per user");
await db.query("insert into applications(user_id,company,title,job_id,resume_id) values($1,'c','t',$2,$3)", [u, j, r]);
await db.query("delete from resumes where id=$1", [r]);
assert.equal((await one("select resume_id from applications")).resume_id, null, "deleting a resume keeps the application (SET NULL)");
await db.query("delete from users where id=$1", [u]);
const left = await one("select (select count(*) from applications)::int a,(select count(*) from interview_sessions)::int i,(select count(*) from coach_conversations)::int c,(select count(*) from ats_analyses)::int n");
assert.deepEqual(left, { a: 0, i: 0, c: 0, n: 0 }, "user deletion cascades to everything they own");
console.log("database verify: all checks passed");
