export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { LivePreview } from "./LivePreview";
export { OnePlatform } from "./OnePlatform";
export { ResumeSection } from "./ResumeSection";
export { ATSSection, ATSection } from "./ATSSection";
export { InterviewSection } from "./InterviewSection";
export { CareerReadiness } from "./CareerReadiness";
export { HowItWorks } from "./HowItWorks";
export { JobsSection } from "./JobsSection";
export { Testimonials } from "./Testimonials";
export { Pricing } from "./Pricing";
export { FAQ } from "./FAQ";
export { FinalCTA } from "./FinalCTA";
export { Footer } from "./Footer";